@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.token}}


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jeferson",
  "email": "jeferson4@example.com",
  "password": "1234567"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "jeferson4@example.com",
  "password": "1234567"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "New Question",
  "content": "Question Content"
}