@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jeferson Franco",
  "email": "jeferson@email.com.br",
  "password": "123456"
}

###

